apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-d0fx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-d0fx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0037-app
  name: devfile-sample-d0fx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-d0fx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-d0fx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-d0fx@sha256:7c87d804062551c985938af9517f33a8e1a6fbe489f5f7e654ee0370f8ab3749
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
